# Lecture iii: AI 工具库

*100% 真人手敲制作！不含任何 GPT 成分！*

Made with ♥ by SI100+ (2024) Staff.

## Part 1: NumPy

在前面的课程中，我们了解到了 Python 中的 List 数据结构。在一个列表中，可以有多种类型的数据，列表中存储的 `int` 类型没有范围限制，可以存储任意大小的整数。但是，在机器学习等领域，我们通常需要处理大量的，在一定范围内的数据，因此我们可以按照这个特殊的使用场景对数据结构进行优化。 NumPy 库就提供了这样的功能。

### 1.1 安装 NumPy

使用 `conda` 或 `pip` 安装 NumPy 库

运行下面的代码块以安装此 notebook 要用到的所有库。

下载可能较慢，请耐心等待。

若你在配置环境时创建的虚拟环境名称不是 `si100`，请将下面的代码块中的 `si100` 替换为你的虚拟环境名称。

In [ ]:
!conda activate si100 && pip install -r ./requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

### 1.2 NumPy 的基本对象 -- `ndarray`

NumPy 的核心元素是 `ndarray`，它是一个多维数组。一个 `ndarray` 内的所有元素都是相同类型的，这样可以保证数组的存储效率和运算效率。

In [ ]:
import numpy as np

l = list(range(10))
print(l)

# 从 list 创建一个 numpy 数组
numpy_l = np.array(l)
print(numpy_l)

print()

# 当列表内有多种数据类型时，numpy 会将所有数据类型转换为同一种数据类型
# 我们在后面只会使用到数字类型的数据，这里只是为了演示
l = [1, 2, 3.1415, 'abc']
print(l)

numpy_l = np.array(l)
print(numpy_l)

In [ ]:
# ndarray 支持多维数组
import numpy as np

l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

numpy_l = np.array(l)
print(numpy_l)

### 1.3 `ndarray` 的属性

类似于 Python 的 List，`ndarray` 也可以通过多维的下表索引来访问元素，可以进行切片操作等。

在 NumPy 中，维度个数（嵌套层数）被称为轴（axis），轴的数量被称为秩（rank）。

In [ ]:
# 获取数组的维度

# 无嵌套的数组，形成一维的 ndarray
l = [1, 2, 3, 4, 5]
numpy_l = np.array(l)
print(f"使用 {l} 创建的 numpy_l 维度个数为: {numpy_l.ndim}")

# 嵌套了一层的数组，形成二维的 ndarray
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
numpy_l = np.array(l)
print(f"使用 {l} 创建的 numpy_l 维度个数为: {numpy_l.ndim}")

# 可以使用多维下标访问数组元素
print(f"列表 {l} 的第 2 行第 3 列的元素为: {l[1][2]}")
print(f"numpy 数组 {numpy_l} 的第 2 行第 3 列的元素为: {numpy_l[1, 2]}")

`ndarray` 还有其他可以直接访问的属性：

- `ndarray.shape`：数组的维度，返回一个元组，元组的长度就是数组的秩，每个元素的值对应于数组在该维度上的大小
- `ndarray.size`：数组中元素的总数
- `ndarray.dtype`：数组中元素的类型
- `ndarray.itemsize`：数组中每个元素类型相同，在计算机内以相同大小的二进制数据存储，`itemsize` 属性返回数组中每个元素的大小（以字节为单位）

In [ ]:
import numpy as np

# 创建一个整数类型的数组
l = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(l)
print(f"l 的维度个数为: {l.ndim}")
print(f"每个维度的大小分别为: {l.shape}")
print(f"l 内总元素个数为: {l.size}")
print(f"l 的数据类型为: {l.dtype}")

print()

# 创建一个浮点数类型的数组
floating_l = np.array([[1.1, 2.5, 3.9], [4.3, 5.7, 6.1], [7.5, 8.9, 9.3]])
print(floating_l)
print(f"floating_l 的数据类型为: {floating_l.dtype}")

### 1.4 `ndarray` 的限制

- `ndarray` 中的所有元素都是相同类型的，这样可以保证数组的存储效率和运算效率
- 创建多维数组时，要求每一维的大小相同

In [ ]:
# 尝试用维度不一致的列表创建 ndarray
# l 中的第三个元素是一个长度为 2 的列表，而前两个元素是长度为 3 的列表

l = [[1, 2, 3], [4, 5, 6], [7, 8]]

numpy_l = np.array(l)

numpy_l

### 1.5 创建与修改 `ndarray`

在上面的例子中，我们使用了 `np.array()` 函数，从 Python 的 List 中创建了一个 `ndarray`。除此之外，NumPy 还提供了其他创建 `ndarray` 的方法。

- `np.zeros(shape)`：创建一个指定形状的全 0 数组，`shape` 是一个元组，表示数组的形状，如 `(3, 4)` 表示一个 3 行 4 列的数组，`(2, 3, 4)` 表示一个 2 行 3 列 4 深度的三维数组
- `np.ones(shape)`：创建一个指定形状的全 1 数组
- `np.arange(start, stop, step)`：创建一个一维数组，从 `start` 开始，到 `stop` 结束，步长为 `step`
- `np.linspace(start, stop, num)`：创建一个一维数组，从 `start` 开始，到 `stop` 结束，长度为 `num` 的等差数列，包含 `start` 和 `stop`

In [ ]:
import numpy as np

# 创建一个 3x3 的全 0 数组
l = np.zeros((3, 3))
print("3x3 的全 0 数组:")
print(l)
print()

print(f"函数 zeros 产生的数组的默认数据类型为: {l.dtype}")

print()

# 创建一个 2x3x4 的全 1 数组
l = np.ones((2, 3, 4))
print("2x3x4 的全 1 数组:")
print(l)
print()

# 创建一个 2x5 的全 7 数组
l = np.full((2, 5), 7)
print("2x5 的全 7 数组:")
print(l)
print()

# 创建一个从 0 到 9 的一维数组
l = np.arange(10)
print("从 0 到 9 的一维数组:")
print(l)
print()

# 创建一个从 0 到 2 的等间距长为 9 的数组
l = np.linspace(0, 2, 9)
print("从 0 到 2 的等间距长为 9 的数组:")
print(l)

在创建数组的时候，可以手动指定数组中元素的类型，如 `np.zeros((3, 4), dtype=np.int32)`。

In [ ]:
import numpy as np

# 包含浮点数的列表，但我们指定了数据类型为整数
l = np.array([[1.5, 2.7], [3.9, 4.1], [5.4, 6.2]], dtype=np.int64)

l

In [24]:
import numpy as np

# numpy.ones() 返回的多维数组的数据类型默认为 float64
l = np.ones((2, 3))
print(l)
print(f"l 的数据类型为: {l.dtype}")

# 通过指定 dtype 参数，可以指定返回的数组的数据类型
l = np.ones((2, 3), dtype=np.int64)
print(l)
print(f"l 的数据类型为: {l.dtype}")

[[1. 1. 1.]
 [1. 1. 1.]]
l 的数据类型为: float64
[[1 1 1]
 [1 1 1]]
l 的数据类型为: int64


在创建数组之后，可以通过多种方式修改数组的值，如直接赋值、切片赋值等。

我们还可以使用 `np.reshape()` 函数改变数组的形状，但是要注意，改变形状之后，数组的元素个数不能发生变化。

如，一个 4x6 的数组，可以改变为 3x8 的数组，但是不能改变为 5x5 的数组。

In [25]:
import numpy as np

l = np.arange(24)
print("通过 arange 创建的一维数组:")
print(l)

# 将一维数组转换为 4x6 的二维数组
l = l.reshape(4, 6)
print("通过 reshape 转换为 4x6 的二维数组:")
print(l)

通过 arange 创建的一维数组:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
通过 reshape 转换为 4x6 的二维数组:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [26]:
import numpy as np

l = np.arange(24)
print("通过 arange 创建的一维数组:")
print(l)

# 只有变化后元素个数与原数组元素个数相等时，reshape 才能成功

l = l.reshape(5, 5)

通过 arange 创建的一维数组:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


ValueError: cannot reshape array of size 24 into shape (5,5)

### 1.6 `ndarray` 的运算

`ndarray` 之间可以进行算术运算，运算规则和 Python 中的 List 不同，两个 `ndarray` 对应位置的元素会进行相应的运算，而 `ndarray` 和一个数进行运算时，会对 `ndarray` 中的每一个元素进行相应的运算。

In [29]:
import numpy as np

a = np.arange(9).reshape(3, 3)
b = np.ones((3, 3), dtype=np.int64)

print("a:")
print(a)

print("b:")
print(b)

# 对应元素相加
c = a + b

print("a + b:")
print(c)

print()

# 对应元素相乘
c = a * b

print("a * b:")
print(c)

print()

# 数组内每个元素与一个标量进行运算
c = a + 5

print("a 内每个元素加 5:")
print(c)

a:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
b:
[[1 1 1]
 [1 1 1]
 [1 1 1]]
a + b:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

a * b:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

a 内每个元素加 5:
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [30]:
import numpy as np

# 特殊运算，矩阵乘法
a = np.arange(1, 13).reshape(3, 4)
b = np.arange(1, 13).reshape(4, 3)

print("a:")
print(a)

print("b:")
print(b)

c = np.dot(a, b)
print("a 与 b 的矩阵乘法结果:")
print(c)

a:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
b:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
a 与 b 的矩阵乘法结果:
[[ 70  80  90]
 [158 184 210]
 [246 288 330]]


可以在 https://numpy.org/doc/stable/user/quickstart.html 查询 NumPy 的更多基础功能。

## Part 2: PyTorch